# -*- coding: utf-8 -*-
"""4112029001_HW1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1AH-lupkGE8H1uHSEFLmCOTVS8rL3hpxW
"""

x = 5 #定義一個變數x定將其設定為5
print(f"變數x的值是:{x}") #輸出變數x的值
print(f"變數x的記憶體地址是:{id(x)}") #輸出變數x記憶體位址